import type { Metadata } from "next";
import Link from "next/link";
import { deployment } from "@/lib/site";
export const metadata: Metadata = { title: "Stello nedir?" };
export default function Overview() {
  return <article className="prose"><p className="eyebrow">BAŞLARKEN</p><h1>Banka havalesinden<br />kontrat çağrısına.</h1><p className="intro">Stello, Soroban uygulamalarına banka havalesiyle giriş ve IBAN’a geri çekim akışı ekleyen bir TypeScript SDK ve paylaşılan router kontratıdır.</p>
    <div className="callout"><strong>Bugün ne çalışıyor?</strong><p>Stellar testnet, USDC ve Türk lirası akışını simüle eden mock anchor. Paket yerel arşiv olarak kurulabilir. npm yayını ve herkese açık relay adresi ayrı yayın adımlarıdır.</p></div>
    <h2>Bir ödeme nasıl ilerler?</h2><ol className="explain-list"><li><strong>SDK bir ticket açar.</strong> Kullanıcı, hedef rota ve en fazla 64 baytlık uygulama argümanı router’a kaydedilir.</li><li><strong>Anchor ödeme bilgilerini verir.</strong> Kullanıcı IBAN ve referans kodunu görür. Mock ortamda banka havalesi simüle edilir.</li><li><strong>Ödeme landing hesabına gelir.</strong> Muxed adresin kimliği, ödemeyi ticket ile eşleştirir.</li><li><strong>Relay router’ı çağırır.</strong> Router, USDC’yi hedef kontrata aktarır ve aynı transaction içinde <code>on_deposit</code> çağırır.</li><li><strong>SDK sonucu okur.</strong> <code>Dispatched</code> eventi, hedefin çağrıldığını ve döndürdüğü <code>accepted</code> sonucunu bildirir.</li></ol>
    <h2>Hangi parça kime ait?</h2><div className="table-scroll"><table><thead><tr><th>Stello</th><th>Entegre eden uygulama</th></tr></thead><tbody><tr><td>Router, ticket ve ödeme yönlendirmesi</td><td>Hedef kontrat ve iş kuralları</td></tr><tr><td>Anchor istemcisi ve SDK</td><td>Arayüz ve kullanıcı anahtarının saklanması</td></tr><tr><td>Landing hesabı ve relay işletimi</td><td>Rota kimliği, argüman biçimi ve sonuç ekranı</td></tr></tbody></table></div>
    <h2>Güven modeli</h2><p>Anchor ve relay güvenilen taraflardır. Para, dispatch öncesinde landing hesabında bulunur; relay miktarı router’a bildirir. Router ödeme referansını kaydeder ve token aktarımıyla hedef çağrısını atomik gerçekleştirir.</p><p><code>accepted: false</code> otomatik olarak router’ın para iade ettiği anlamına gelmez. İadeyi hedef kontrat gerçekleştirmelidir. Hedef hata verirse aktarım ve kayıt geri alınır.</p><p>Testnet hesapları Friendbot ile fonlanır. Mainnet için rezerv ve ücret sponsorluğu, gerçek anchor/KYC, anahtar kurtarma ve relay işletimi ayrıca tasarlanmalıdır.</p>
    <h2>Testnet kaydı</h2><p>Depodaki deployment kaydına göre router:</p><a className="address-link" href={`https://stellar.expert/explorer/testnet/contract/${deployment.routerId}`} target="_blank" rel="noreferrer">{deployment.routerId} ↗</a><p className="muted">Bu kayıt canlı sağlık kontrolü değildir; testnet sıfırlanırsa deployment yenilenmelidir.</p>
    <Link className="next-doc" href="/docs/installation"><span>SIRADAKİ</span>SDK’yı kur ↗</Link>
  </article>;
}
